web/api/urls.py
from django.urls import path

from api.views import(
    DiciplineDetailView,
    DiciplineListView,
    GroupDetailView,
    GroupListView,
    StudentDetailView,
    StudentListView,
    TeacherDetailView,
    TeacherListView,
    UserDetailView,
    UserListView,
) 

urlpatterns = [
    path('users/', UserListView.as_view()),
    path('users/<int:pk>', UserDetailView.as_view()),
    path('groups/', GroupListView.as_view()),
    path('groups/<int:pk>', GroupDetailView.as_view()),
    path('students/', StudentListView.as_view()),
    path('students/<int:pk>', StudentDetailView.as_view()),
    path('diciplines/', DiciplineListView.as_view()),
    path('diciplines/<int:pk>', DiciplineDetailView.as_view()),
    path('teachers/', TeacherListView.as_view()),
    path('teachers/<int:pk>', TeacherDetailView.as_view()),
]

web/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

web/main/models.py
from tabnanny import verbose
from django.db import models
import datetime
from django.contrib.auth import get_user_model

User = get_user_model()

class Bell(models.Model):
    pair = models.PositiveSmallIntegerField("Номер пары", default=0)
    start = models.TimeField("Начало")
    duration = models.DurationField("Длительность")

    def __str__(self) -> str:
        return f"Звонок на {self.pair} в {self.start}"

    class Meta:
        verbose_name_plural = "Звонки"
        verbose_name = "Звонок"

class Mark(models.Model):
    mark = models.PositiveSmallIntegerField("Отметка", default=0)
    dicipline = models.ForeignKey('Dicipline', related_name='marks', verbose_name="Дисциплины", null=True, on_delete=models.SET_NULL)
    student = models.ForeignKey('Student', related_name='marks', verbose_name='Студент', null=True, on_delete=models.SET_NULL)
    date = models.DateField("Date", default=datetime.date.today)

    class Meta:
        verbose_name = "Отметка"
        verbose_name_plural = "Отметки"

class Dicipline(models.Model):
    title = models.CharField("Название", max_length=200)

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name_plural = "Дисциплины"
        verbose_name = "Дисциплина"


class Teacher(models.Model):
    user = models.OneToOneField(User, null=True, related_name='teacher', on_delete=models.CASCADE, blank=True)
    name = models.CharField("Имя", max_length=50)
    second_name = models.CharField("Отчество", max_length=50)
    surname = models.CharField("Фамилия", max_length=50)
    photo = models.ImageField("Фото",upload_to = "media/teachers/", blank=True, null=True)
    rang = models.CharField("Должность", max_length=200)
    email = models.EmailField("Электронная почта", max_length=200)
    diciplines = models.ManyToManyField(Dicipline, verbose_name="Дисциплины")

    def __str__(self) -> str:
        return f'{self.surname} {self.name} {self.second_name}'

    class Meta:
        verbose_name_plural = "Преподаватели"
        verbose_name = "Преподаватель"


class Group(models.Model):
    number = models.CharField("Номер", max_length=6)
    faculty = models.CharField("Факультет", max_length=200)
    specialisation = models.CharField("Специальность", max_length=200)
    course = models.PositiveSmallIntegerField("Курс", default=0)

    def __str__(self) -> str:
        return self.number

    class Meta:
        verbose_name_plural = "Группы"
        verbose_name = "Группа"

class Schedule(models.Model):
    DAY_CHOICE = (
        (0,'Понедельник'),
        (1,'Вторник'),
        (2,'Среда'),
        (3,'Четверг'),
        (4,'Пятница'),
        (5,'Суббота'),
        (6,'Воскресенье'),
    )

    TYPE_CHOICE = (
        ('лк', "Лекция"),
        ('пз', "Практическое занятие"),
        ('лр', "Лабораторная работа"),
    )

    group = models.ForeignKey(Group, verbose_name="Группа", null=True, on_delete=models.SET_NULL)
    teacher = models.ForeignKey(Teacher, verbose_name="Преподаватель", null=True, on_delete=models.SET_NULL)
    dicipline = models.ForeignKey(Dicipline, verbose_name="Дисциплина", null=True, on_delete=models.SET_NULL)
    bell = models.ForeignKey(Bell, verbose_name="Звонок", null=True, on_delete=models.SET_NULL)
    classroom = models.PositiveSmallIntegerField("Аудитория", default=0)
    day = models.PositiveSmallIntegerField("День недели", default=0, choices=DAY_CHOICE)
    week = models.PositiveSmallIntegerField("Неделя", default=0)
    pair_type = models.CharField("Тип", max_length=50, default='', choices=TYPE_CHOICE)

    def __str__(self) -> str:
        return f"Пара #{self.bell.pair} {self.dicipline} [{self.get_day_display()} {self.week}]"

    class Meta:
        verbose_name = "Расписание"
        verbose_name_plural = "Расписание"

class Student(models.Model):
    user = models.OneToOneField(User, null=True, related_name='student', on_delete=models.CASCADE, blank=True)
    name = models.CharField("Имя", max_length=50)
    second_name = models.CharField("Отчество", max_length=50)
    surname = models.CharField("Фамилия", max_length=50)
    photo = models.ImageField("Фото",upload_to = "media/students/", null=True, blank=True)
    number = models.CharField("Студенческий билет", max_length=15)
    group = models.ForeignKey(Group, related_name='students', verbose_name="Номер группы", null=True, on_delete=models.SET_NULL, blank=True)

    def __str__(self) -> str:
        return f'{self.surname} {self.name} {self.second_name}'

    @property
    def get_full_name(self):
        return f'{self.surname} {self.name} {self.second_name}'

    @property
    def rating(self):
        s = 0
        for mark in self.exam_marks.all():
            s += mark.mark
        if self.exam_marks.count():
            return s / self.exam_marks.count()
        return 0

    class Meta:
        ordering = ('surname','name','second_name')
        verbose_name_plural = "Студенты"
        verbose_name = "Студент"

class Exam(models.Model):
    group = models.ForeignKey(Group, verbose_name="Номер группы", null=True, on_delete=models.CASCADE, blank=True) 
    dicipline = models.OneToOneField(Dicipline, verbose_name="Дисциплина", null=True, on_delete=models.CASCADE, blank=True)
    exam_type = models.CharField("Тип", max_length=50)
    classroom = models.PositiveSmallIntegerField("Аудитория", default=0)
    day = models.PositiveSmallIntegerField("День недели", default=0)
    bell = models.ForeignKey(Bell, verbose_name="Звонок", null=True, on_delete=models.SET_NULL)
    teacher = models.ForeignKey(Teacher, verbose_name="Преподаватель", null=True, on_delete=models.SET_NULL)
    date = models.DateField("Date", default=datetime.date.today)

    def __str__(self) -> str:
        return f"Экзамен по {self.dicipline}"

    class Meta:
        verbose_name_plural = "Экзамены"
        verbose_name = "Экзамен"

class ExamMark(models.Model):
    mark = models.PositiveSmallIntegerField("Отметка", default=0)
    exam = models.ForeignKey('Exam', related_name='exam_marks', verbose_name="Отметки", null=True, on_delete=models.CASCADE)    
    student = models.ForeignKey('Student', related_name='exam_marks', verbose_name='Студент', null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Экзаменационная отметка"
        verbose_name_plural = "Экзаменационные отметки"

class Notification(models.Model):
    teacher = models.ForeignKey(Teacher, related_name="notifications", verbose_name="Преподаватель", null=True, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, related_name="notifications", verbose_name="Преподаватель", null=True, on_delete=models.CASCADE)
    message = models.TextField("Сообщение")

    def __str__(self)->str:
        return f'Message from {self.teacher} to group {self.group}'

class Missings(models.Model):
    hours = models.PositiveSmallIntegerField("Количество", default=0)
    dicipline = models.ForeignKey(Dicipline, related_name="missings", verbose_name="Пропуски", null=True, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, related_name="missings", verbose_name="Пропуски", null=True, on_delete=models.CASCADE)
    date = models.DateField("Date", default=datetime.date.today)

    class Meta:
        verbose_name = "Часы пропусков"

web/templates/exams.html
{% extends 'wrapper.html'%}

{% block title %}
    Schedule
{% endblock %}

{% block content %}
<table class="table table-dark table-striped" >
    {% for exam in exams %}
    <tr>
        <td>
            {{ exam.exam.dicipline}}
        </td>
        <td>
            {{ exam.exam.exam_type}}
        </td>
        <td>
            {{ exam.mark }}
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

web/templates/group_schedule.html
{% extends 'wrapper.html'%}

{% block title %}
    Schedule
{% endblock %}

{% block content %}
<h1>Расписание группы {{group.number}}</h1>
<hr>
<nav class="py-3">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
       {% for schedule_list in schedule %}
       {% if schedule_list %}
       <button class="nav-link" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-{{schedule_list.0.week}}"
          type="button" role="tab" aria-controls="nav-home" aria-selected="true">Неделя {{schedule_list.0.week}}</button>
       {% endif %}
       {% endfor %}
    </div>
 </nav>
<div class="tab-content" id="nav-tabContent">
    {% for schedule_list in schedule %}
    <div class="tab-pane fade" id="nav-{{schedule_list.0.week}}" role="tabpanel" aria-labelledby="nav-home-tab">
       {% if schedule_list %}
       <table class="table">
          <thead>
             <th>День недели</th>
             <th>Дисциплина</th>
             <th>Преподаватель</th>
             <th>Начало пары</th>
          </thead>
          <tbody>
             {% for pair in schedule_list %}
             <tr>
                <td>
                   {{pair.get_day_display}}
                </td>
                <td>
                   {{ pair.dicipline }}
                </td>
                <td>
                   {{ pair.teacher }}
                </td>
                <td>
                   {{ pair.bell.start }}
                </td>
             </tr>
             {% endfor %}
          </tbody>
       </table>
       {% else %}
       There is no schedule
       {% endif %}
    </div>
    {% endfor %}
 </div>
{% endblock %}

web/templates/main_window.html
{% extends 'wrapper.html' %}

{% block title %}
Welcome page
{% endblock %}

{% block content %}
<h1 style="text-align: center;">Добро пожаловать в приложение "Успеваемость"!</h1>
<hr>
<p style="text-align: center;">Данное приложение направлено на отслеживание своего учебного процесса студентами.</p>
{% endblock %}

web/templates/marks.html
{% extends 'wrapper.html'%}

{% block title %}
    Marks
{% endblock %}

{% block content %}
    <h1>Ваши отметки</h1>
    <hr>
    <table class="table table-striped">
        <thead>
            <th>Предмет</th>
            <th>Пропуски</th>
            <th>Отметки</th>
        </thead>
        <tbody>
            {% for dicipline, item in marks.items %}
            {% with miss=item.0 marks=item.1 %}
            <tr>
                <td>{{dicipline}}</td>
                <td>{{  miss }}</td>
                {% for mark in marks %}
                <td>{{mark}}</td>
                {% endfor %}
                
            </tr>
            {% endwith %}
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

web/templates/notify.html
{% extends "wrapper.html" %}

{% block title %}
Notifications list
{% endblock %}

{% block content %}
<h1>Сообщения</h1>
<hr>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Текст сообщения</th>
            <th>Автор</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for notification in object_list %}
        <tr>
            <td>{{notification.id}}</td>
            <td>{{notification.message}}</td>
            <td>{{notification.teacher}}</td>
            <td><a href="/account/notifications/{{ notification.id }}/">Просмотр</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

web/templates/password_change_done.html
{% extends "wrapper.html" %}
{% load i18n %}

{% block title %}
    {{ title }}
    {% endblock %}

{% block content %}
    <p>{% trans "Пароль успешно изменён" %}</p>
    <a class="btn btn-success" href="/account/edit">Назад</a>
{% endblock %}

web/templates/schedule_list.html
{% extends 'wrapper.html' %}

{% block title %}
Schedule
{% endblock %}

{% block content %}
{% if group %}
<h1>Расписание группы {{group.number}}</h1>
{% else %}
<h1>Расписание групп</h1>
{% endif %}
<hr>
<div class="input-group mb-3">
   <input id="group-number" type="text" class="form-control" placeholder="Введите номер группы..."
      aria-label="Recipient's username" aria-describedby="button-addon2">
   <a class="btn btn-outline-primary" id="check-btn">Просмотреть расписание</a>
</div>
<hr>
<script>
   let text = document.getElementById("group-number");
   let btn = document.getElementById("check-btn");

   text.addEventListener("keyup", () => {
      let number = text.value;
      btn.setAttribute("href", `/schedule/${number}`);
   });
</script>

<nav class="py-3">
   <div class="nav nav-tabs" id="nav-tab" role="tablist">
      {% for schedule_list in schedule %}
      {% if schedule_list %}
      <button class="nav-link" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-{{schedule_list.0.week}}"
         type="button" role="tab" aria-controls="nav-home" aria-selected="true">Неделя {{schedule_list.0.week}}</button>
      {% endif %}
      {% endfor %}
   </div>
</nav>
<div class="tab-content" id="nav-tabContent">
   {% for schedule_list in schedule %}
   <div class="tab-pane fade" id="nav-{{schedule_list.0.week}}" role="tabpanel" aria-labelledby="nav-home-tab">
      {% if schedule_list %}
      <table class="table">
         <thead>
            <th>День недели</th>
            <th>Дисциплина</th>
            <th>Преподаватель</th>
            <th>Начало пары</th>
         </thead>
         <tbody>
            {% for pair in schedule_list %}
            <tr>
               <td>
                  {{pair.get_day_display}}
               </td>
               <td>
                  {{ pair.dicipline }}
               </td>
               <td>
                  {{ pair.teacher }}
               </td>
               <td>
                  {{ pair.bell.start }}
               </td>
            </tr>
            {% endfor %}
         </tbody>
      </table>
      {% else %}
      There is no schedule
      {% endif %}
   </div>
   {% endfor %}
</div>

{% endblock %}

web/templates/student_notification.html
{% extends "wrapper.html" %}

{% block title %}
Notification
{% endblock %}

{% block content %}
<div class="card text-center">
    <div class="card-header">
        <h5>
            Сообщение от {{notification.teacher}}<br>
            группе {{notification.group}}
        </h5>
    </div>
    <div class="card-body">
        <p class="card-text">
            {{notification.message}}
        </p>
    </div>
</div>
{% endblock %}

web/templates/teacher_del_notification.html
{% extends "wrapper.html" %}

{% block title %}
Notifications list
{% endblock %}

{% block content %}
    <form method="POST">
        {%csrf_token%}
        <button type="submit">
            Удалить
        </button>
    </form>
{% endblock %}

web/templates/teacher_exam_mark.html
{% extends "wrapper.html" %}

{% block title %}
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">
            Добавить   
        </button>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>ФИО</th>
                <th>Отметка</th>
            </tr>
        </thead>
        <tbody>
            {% for student, mark in exam_marks.items %}
                <tr>
                    <td>
                        {{ student.surname}}
                    </td>
                        <td>
                            {{ mark }}
                        </td>
                
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

web/templates/teacher_exams.html
{% extends "wrapper.html" %}

{% block title %}
{% endblock %}

{% block content %}
<h1>Экзамены</h1>
<ol>
    {% for exam in exams %}
    <li>
        <a href="/teachers/exams/{{group.number}}/{{exam.dicipline__id}}/">
            {{ exam.dicipline__title }}
        </a>
    </li>
    {% endfor %}
</ol>
{% endblock %}

web/templates/teacher_exams_group.html
{% extends "wrapper.html" %}

{% block title %}
{% endblock %}

{% block content %}
<h1>Ваши группы</h1>
<ul>
    {% for group in groups %}
    <li>
        <a href="/teachers/exams/{{ group.group__number }}">
            {{ group.group__number }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

web/templates/teacher_notification.html
{% extends "wrapper.html" %}

{% block title %}
Notification
{% endblock %}

{% block content %}
    <div class="card text-center">
        <div class="card-header">
            <h5>
                Сообщение от {{notification.teacher}}<br>
                группе {{notification.group}}
            </h5>
        </div>
        <div class="card-body">
            <p class="card-text">
                {{notification.message}}
            </p>
        </div>
        <div class="card-footer">
            <a class="btn btn-success" href="/teachers/notifications/{{ notification.id }}/update">
                Редактировать
            </a>
        
            <a class="btn btn-danger" href="/teachers/notifications/{{ notification.id }}/delete">
                Удалить
            </a>
        </div>
    </div>

{% endblock %}

web/templates/wrapper.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>

<body bgcolor="#edd7e8">
    {% include "headers/header.html" %}
    <div class="container">
        <div class="row">
          <div class="col-md-2">
          </div>
          <div class="col-md-8 gy-4">
            {% block content %}
            {% endblock %}
          </div>
          <div class="col-md-2">
          </div>
        </div>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>

</html>